import { defineStyleConfig } from "@chakra-ui/react";
import { textStyleB1 } from "../foundation/textStyles";

export const Button = defineStyleConfig({
  baseStyle: {
    borderRadius: "4px",
    boxShadow: "0px 2px 3px rgba(0, 0, 0, 0.25)",
    cursor: "default",
    _disabled: {
      opacity: 0.2,
      boxShadow: "none",
      cursor: "not-allowed",
    },
    _hover: {
      cursor: "pointer",
      _disabled: {
        cursor: "not-allowed",
      },
    },
  },
  variants: {
    controlButton: {
      height: "25px",
      flexGrow: "1",
      bg: "sc_black.400",
      borderRadius: "2px",
      color: "sc_white.200",
      padding: "sm",
      gap: "sm",
      minWidth: "25px",
      minHeight: "25px",
      ...textStyleB1,
      _hover: {
        bg: "sc_black.300",
        color: "sc_white.50",
        _disabled: {
          bg: "sc_black.400",
          color: "sc_white.200",
        },
      },
      _disabled: {
        bg: "sc_black.400",
        color: "sc_white.200",
      },
    },
    controlButtonFocused: {
      height: "25px",
      flexGrow: "1",
      bg: "sc_yellow.300",
      borderRadius: "2px",
      color: "sc_black.800",
      padding: "sm",
      gap: "sm",
      minWidth: "25px",
      minHeight: "25px",
      ...textStyleB1,
      _hover: {
        bg: "sc_yellow.100",
        color: "sc_black.900",
        _disabled: {
          bg: "sc_yellow.300",
          color: "sc_black.800",
        },
      },
      _disabled: {
        bg: "sc_yellow.300",
        color: "sc_black.800",
      },
    },
    setupStatusButtonDefault: {
      minWidth: "25px",
      width: "25px",
      height: "25px",
      maxWidth: "25px",
      flexGrow: "1",
      bg: "transparent",
      boxShadow: "none",
      borderRadius: "2px",
      color: "sc_white.200",
      padding: "sm",
      gap: "sm",
      ...textStyleB1,
      _hover: {
        bg: "sc_black.300",
        color: "sc_white.50",
        _disabled: {
          bg: "transparent",
          color: "sc_white.200",
        },
      },
      _disabled: {
        bg: "transparent",
        color: "sc_white.200",
      },
    },
    setupStatusButtonSuccess: {
      minWidth: "25px",
      width: "25px",
      height: "25px",
      maxWidth: "25px",
      transition: "max-width 0.5s ease-in-out",
      flexGrow: "1",
      bg: "transparent",
      boxShadow: "none",
      borderRadius: "2px",
      color: "sc_green.300",
      padding: "sm",
      gap: "sm",
      minHeight: "25px",
      ...textStyleB1,
      _hover: {
        bg: "sc_greenAlpha.25",
        color: "sc_green.200",
        _disabled: {
          bg: "sc_greenAlpha.15",
          color: "sc_green.300",
        },
      },
      _disabled: {
        bg: "sc_greenAlpha.15",
        color: "sc_green.300",
      },
    },
    setupStatusButtonError: {
      minWidth: "25px",
      width: "25px",
      height: "25px",
      maxWidth: "25px",
      flexGrow: "1",
      bg: "sc_redAlpha.15",
      borderRadius: "2px",
      color: "sc_red.300",
      padding: "sm",
      gap: "sm",
      ...textStyleB1,
      _hover: {
        bg: "sc_redAlpha.25",
        color: "sc_red.200",
        _disabled: {
          bg: "sc_redAlpha.15",
          color: "sc_red.300",
        },
      },
      _disabled: {
        bg: "sc_redAlpha.15",
        color: "sc_red.400",
      },
    },
    primaryButton: {
      bg: "sc_yellow.300",
      color: "sc_black.800",
      height: "34px",
      width: "100%",
      alignItems: "center",
      textAlign: "center",
      padding: "md",
      gap: "md",

      ...textStyleB1,
      _hover: {
        bg: "sc_yellow.100",
        color: "sc_black.900",
        _disabled: {
          bg: "sc_yellow.300",
          color: "sc_black.800",
        },
      },
      _disabled: {
        bg: "sc_yellow.300",
        color: "sc_black.800",
      },
    },
    secondaryButton: {
      bg: "sc_green.300",
      color: "sc_black.800",
      height: "34px",
      alignItems: "center",
      textAlign: "center",
      width: "180px",
      padding: "md",
      gap: "md",
      ...textStyleB1,
      _hover: {
        bg: "sc_green.100",
        color: "sc_black.900",
        _disabled: {
          bg: "sc_green.300",
          color: "sc_black.800",
        },
      },
      _disabled: {
        bg: "sc_green.300",
        color: "sc_black.800",
      },
    },
    standardButton: {
      bg: "sc_black.900",
      color: "sc_white.200",
      height: "34px",
      width: "100%",
      alignItems: "center",
      textAlign: "center",
      padding: "md",
      gap: "md",
      ...textStyleB1,
      _hover: {
        bg: "sc_black.800",
        color: "sc_white.100",
        _disabled: {
          bg: "sc_black.900",
          color: "sc_white.200",
        },
      },
      _disabled: {
        bg: "sc_black.900",
        color: "sc_white.200",
      },
    },
    levelButton: {
      boxShadow: "none",
      flexGrow: "1",
      bg: "transparent",
      borderRadius: "0px",
      color: "sc_white.200",
      alignItems: "center",
      gap: "sm",
      minWidth: "0px",
      width: "100%",
      height: "118px",
      minHeight: "108px",
      ...textStyleB1,
      _hover: {
        color: "sc_white.50",
        _disabled: {
          color: "sc_white.200",
        },
      },
      _disabled: {
        color: "sc_white.200",
      },
    },
    playControlIconButton: {
      bg: "transparent",
      color: "sc_white.50",
      _hover: {
        bg: "transparent",
        color: "sc_green.500",
        _disabled: {
          bg: "transparent",
          color: "sc_white.50",
        },
      },
      _disabled: {
        color: "sc_white.50",
      },
    },
    iconGhostButton: {
      bg: "transparent",
      color: "sc_white.200",
      boxShadow: "none",
      minWidth: "1px",
      minHeight: "1px",
      padding: "sm",
      height: "10px",
      width: "10px",
      gap: "xs",
      _hover: {
        bg: "transparent",
        color: "sc_white.100",
        boxShadow: "none",
        _disabled: {
          bg: "transparent",
          color: "sc_white.200",
        },
      },
      _disabled: {
        bg: "transparent",
        color: "sc_white.100",
        boxShadow: "none",
      },
    },
    iconButton: {
      color: "sc_white.200",
      backgroundColor: "sc_black.400",
      boxSize: "25px",
      padding: "5px",
      borderRadius: "2px",
      minWidth: "0px",
      _hover: {
        bg: "sc_black.300",
        color: "sc_white.50",
      },
      _disabled: {
        opacity: "0.2",
        pointerEvents: "none",
      },
    },
  },
});
